import * as React from "react";
import { supabase } from "@/integrations/supabase/client";

export type Language = "EN" | "FR" | "RW";

const translations = {
  EN: {
    // Header / nav
    search: "Search products, brands, categories...",
    cart: "Cart",
    signIn: "Sign In",
    signUp: "Sign Up",
    signOut: "Sign Out",
    categories: "Categories",
    allProducts: "All Products",
    home: "Home",
    products: "Products",
    orders: "My Orders",
    branchDashboard: "Branch dashboard",
    adminRoles: "Admin · Roles",
    account: "Account",
    location: "Kigali, Rwanda",
    // Landing
    heroTitleA: "Groceries in",
    heroTitleB: "minutes.",
    heroSubtitle: "Shop Rwanda's freshest groceries with instant MoMo checkout and pick-up at your nearest Simba branch.",
    startShopping: "Start Shopping",
    fastDelivery: "Fast Pick-up",
    fastDeliveryDesc: "Ready in under 60 minutes",
    securePayment: "Secure Payment",
    securePaymentDesc: "MoMo & card supported",
    convenientPickup: "9 Branches",
    convenientPickupDesc: "Pick up across Kigali",
    shopByCategory: "Shop by Category",
    featuredProducts: "Featured Products",
    viewAll: "View all",
    trustedBy: "Trusted by 10,000+ Kigali shoppers",
    ourBranches: "Our branches",
    // Product card
    addToCart: "Add to Cart",
    outOfStock: "Out of Stock",
    inStock: "In Stock",
    // Cart
    emptyCart: "Your cart is empty",
    exploreProducts: "Explore Products",
    subtotal: "Subtotal",
    delivery: "Delivery",
    free: "FREE",
    total: "Total",
    proceedToPay: "Proceed to Pay",
    loginToCheckout: "Log in to complete your order",
    checkout: "Checkout",
    // Sort
    sortBy: "Sort by",
    popularity: "Popularity",
    lowToHigh: "Price: Low to High",
    highToLow: "Price: High to Low",
    noProducts: "No products match your search.",
    productsFound: "products",
    // Recommended
    recommended: "Recommended for you",
    // Checkout
    pickupBranch: "Pick-up branch",
    selectBranch: "Select a branch",
    chooseBranch: "Choose your pick-up branch",
    branchHint: "We'll prepare your order for collection here.",
    pickupTime: "Pick-up time",
    pickupToday: "Today",
    pickupTomorrow: "Tomorrow",
    chooseTime: "Choose a pick-up time",
    yourDetails: "Your details",
    fullName: "Full name",
    phoneNumber: "Phone number",
    momoNumber: "MoMo phone number",
    momoHint: "A payment prompt will be sent to this number.",
    notesOptional: "Order notes (optional)",
    notesPlaceholder: "Any special instructions...",
    deposit: "Pick-up deposit",
    depositExplain: "A small refundable deposit holds your order so staff don't pack it for nothing.",
    payDeposit: "Pay deposit",
    processing: "Processing...",
    momoPrompt: "MoMo prompt sent",
    momoPromptDesc: "Approve the prompt on your phone to confirm the deposit.",
    confirmPayment: "Confirm payment",
    cancel: "Cancel",
    orderPlaced: "Order placed!",
    orderPlacedDesc: "Your branch has been notified and will start preparing your order.",
    continueShopping: "Continue shopping",
    orderSummary: "Order summary",
    subtotalLabel: "Subtotal",
    payNow: "Pay now",
    minOrder: "Add at least one item to checkout.",
    invalidMomo: "Enter a valid Rwandan MoMo number (e.g. 07XXXXXXXX)",
    // Auth
    welcomeBack: "Welcome back",
    createAccount: "Create your account",
    signInDesc: "Sign in to continue shopping",
    signUpDesc: "Join Simba in seconds",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm password",
    forgotPassword: "Forgot password?",
    continueWithGoogle: "Continue with Google",
    orContinueWith: "or continue with email",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    register: "Register",
    login: "Sign in",
    backToShop: "Back to shop",
    resetPassword: "Reset your password",
    resetPasswordDesc: "Enter your email to receive a reset link.",
    sendResetLink: "Send reset link",
    resetLinkSent: "Check your inbox for the reset link.",
    setNewPassword: "Set a new password",
    newPassword: "New password",
    updatePassword: "Update password",
    passwordUpdated: "Password updated. You're signed in.",
    invalidCredentials: "Invalid email or password",
    passwordTooShort: "Password must be at least 6 characters",
    passwordsMismatch: "Passwords do not match",
    accountCreated: "Account created. Welcome to Simba!",
    enterValidEmail: "Enter a valid email address",
    // Orders page
    myOrders: "My Orders",
    noOrders: "No orders yet",
    startShoppingDesc: "Start shopping to see your orders here.",
    browseProducts: "Browse products",
    pickupAt: "Pick-up at",
    rateBranchHint: "You can rate this branch once your order is picked up.",
    // Staff dashboard
    dashTitle: "Branch dashboard",
    dashAdmin: "Admin · all branches",
    dashManager: "Manager view",
    dashStaff: "Staff view",
    refresh: "Refresh",
    ordersTab: "Orders",
    inventoryTab: "Inventory",
    bucketNew: "New",
    bucketPreparing: "Preparing",
    bucketReady: "Ready for pick-up",
    bucketDone: "Completed",
    accept: "Accept",
    startPreparing: "Start preparing",
    markReady: "Mark ready",
    markPickedUp: "Mark picked up",
    flag: "Flag",
    flagCustomer: "Flag customer",
    assignToStaff: "Assign to staff...",
    showDetails: "Show details",
    hideDetails: "Hide details",
    me: "Me",
    noStaff: "No staff yet",
    items: "items",
    item: "item",
    staffOnly: "Staff access only",
    staffOnlyDesc: "You need branch staff or manager permissions to view this dashboard. Ask your admin to grant access.",
    goHome: "Go home",
    // Inventory panel
    searchProductOrId: "Search product name or ID...",
    addProduct: "Add product",
    addProductTitle: "Add product to this branch",
    initialStock: "Initial stock",
    save: "Save",
    available: "Available",
    outOfStockLabel: "Out of stock",
    remove: "Remove",
    confirmRemove: "Remove this product from your branch inventory?",
    stockUpdated: "Stock updated",
    productAdded: "Product added to branch",
    productRemoved: "Product removed",
    noInventory: "No products in this branch yet. Click 'Add product' to start stocking.",
    // Admin
    adminTitle: "Role assignment",
    adminDesc: "Promote users to branch manager or staff.",
    adminOnly: "Admin only",
    adminOnlyDesc: "You don't have permission to access this page.",
    user: "User",
    role: "Role",
    branch: "Branch",
    grantRole: "Grant role",
    granting: "Granting...",
    existingRoles: "Existing roles",
    yourUserId: "Your user ID:",
    branchStaff: "Branch staff",
    branchManager: "Branch manager",
    admin: "Admin",
    customer: "Customer",
    selectUser: "Select a user...",
    selectBranchPlaceholder: "Select branch",
    pretranslate: "Pre-translate product catalog",
    pretranslateDesc: "Run once: translate all product names & categories into FR + RW so they update instantly across the site.",
    translating: "Translating...",
    translateAll: "Translate all products",
    translationDone: "Translations cached. Switch language to see results.",
    seedInventory: "Seed branch inventory",
    seedInventoryDesc: "Populate every branch with starter stock from the product catalog (run once).",
    seedNow: "Seed inventory",
    seeded: "Branches stocked.",
    // AI
    askSimba: "Ask Simba AI",
    aiSubtitle: "Your shopping assistant",
    aiGreeting: "Hi! 👋 I'm Simba — your AI shopping assistant. Ask me anything: meal ideas, products, prices, or what's good for breakfast!",
    aiPlaceholder: "Ask anything about products...",
    tryAsking: "Try asking",
    thinking: "thinking...",
    // Reviews
    rateThisBranch: "Rate this branch",
    leaveComment: "Leave a comment (optional)",
    submitReview: "Submit review",
    reviewThanks: "Thanks for your review!",
    alreadyReviewed: "You already reviewed this order.",
  },
  FR: {
    search: "Rechercher des produits, marques...",
    cart: "Panier",
    signIn: "Se connecter",
    signUp: "S'inscrire",
    signOut: "Déconnexion",
    categories: "Catégories",
    allProducts: "Tous les produits",
    home: "Accueil",
    products: "Produits",
    orders: "Mes commandes",
    branchDashboard: "Tableau de bord magasin",
    adminRoles: "Admin · Rôles",
    account: "Compte",
    location: "Kigali, Rwanda",
    heroTitleA: "Vos courses en",
    heroTitleB: "minutes.",
    heroSubtitle: "Achetez les produits les plus frais du Rwanda avec paiement MoMo et retrait dans votre Simba le plus proche.",
    startShopping: "Commencer mes achats",
    fastDelivery: "Retrait Rapide",
    fastDeliveryDesc: "Prêt en moins de 60 minutes",
    securePayment: "Paiement Sécurisé",
    securePaymentDesc: "MoMo & carte acceptés",
    convenientPickup: "9 Magasins",
    convenientPickupDesc: "Retrait partout à Kigali",
    shopByCategory: "Acheter par catégorie",
    featuredProducts: "Produits en vedette",
    viewAll: "Tout voir",
    trustedBy: "Approuvé par 10 000+ clients à Kigali",
    ourBranches: "Nos magasins",
    addToCart: "Ajouter au panier",
    outOfStock: "Rupture de stock",
    inStock: "En stock",
    emptyCart: "Votre panier est vide",
    exploreProducts: "Explorer les produits",
    subtotal: "Sous-total",
    delivery: "Livraison",
    free: "GRATUIT",
    total: "Total",
    proceedToPay: "Procéder au paiement",
    loginToCheckout: "Connectez-vous pour finaliser",
    checkout: "Commander",
    sortBy: "Trier par",
    popularity: "Popularité",
    lowToHigh: "Prix : Croissant",
    highToLow: "Prix : Décroissant",
    noProducts: "Aucun produit ne correspond à votre recherche.",
    productsFound: "produits",
    recommended: "Recommandé pour vous",
    pickupBranch: "Magasin de retrait",
    selectBranch: "Sélectionner un magasin",
    chooseBranch: "Choisissez votre magasin de retrait",
    branchHint: "Nous préparerons votre commande pour le retrait ici.",
    pickupTime: "Heure de retrait",
    pickupToday: "Aujourd'hui",
    pickupTomorrow: "Demain",
    chooseTime: "Choisissez une heure de retrait",
    yourDetails: "Vos coordonnées",
    fullName: "Nom complet",
    phoneNumber: "Numéro de téléphone",
    momoNumber: "Numéro MoMo",
    momoHint: "Une demande de paiement sera envoyée à ce numéro.",
    notesOptional: "Notes de commande (facultatif)",
    notesPlaceholder: "Instructions particulières...",
    deposit: "Acompte de retrait",
    depositExplain: "Un petit acompte garantit votre commande pour que le personnel ne la prépare pas pour rien.",
    payDeposit: "Payer l'acompte",
    processing: "Traitement...",
    momoPrompt: "Demande MoMo envoyée",
    momoPromptDesc: "Approuvez la demande sur votre téléphone pour confirmer l'acompte.",
    confirmPayment: "Confirmer le paiement",
    cancel: "Annuler",
    orderPlaced: "Commande passée !",
    orderPlacedDesc: "Le magasin a été notifié et commence à préparer votre commande.",
    continueShopping: "Continuer mes achats",
    orderSummary: "Résumé de la commande",
    subtotalLabel: "Sous-total",
    payNow: "Payer",
    minOrder: "Ajoutez au moins un article pour commander.",
    invalidMomo: "Entrez un numéro MoMo rwandais valide (ex. 07XXXXXXXX)",
    welcomeBack: "Bon retour",
    createAccount: "Créez votre compte",
    signInDesc: "Connectez-vous pour continuer",
    signUpDesc: "Rejoignez Simba en quelques secondes",
    email: "Email",
    password: "Mot de passe",
    confirmPassword: "Confirmer le mot de passe",
    forgotPassword: "Mot de passe oublié ?",
    continueWithGoogle: "Continuer avec Google",
    orContinueWith: "ou continuer avec email",
    noAccount: "Pas de compte ?",
    haveAccount: "Déjà un compte ?",
    register: "S'inscrire",
    login: "Se connecter",
    backToShop: "Retour à la boutique",
    resetPassword: "Réinitialiser le mot de passe",
    resetPasswordDesc: "Entrez votre email pour recevoir un lien.",
    sendResetLink: "Envoyer le lien",
    resetLinkSent: "Vérifiez votre boîte mail.",
    setNewPassword: "Définir un nouveau mot de passe",
    newPassword: "Nouveau mot de passe",
    updatePassword: "Mettre à jour",
    passwordUpdated: "Mot de passe mis à jour. Vous êtes connecté.",
    invalidCredentials: "Email ou mot de passe invalide",
    passwordTooShort: "Le mot de passe doit faire au moins 6 caractères",
    passwordsMismatch: "Les mots de passe ne correspondent pas",
    accountCreated: "Compte créé. Bienvenue chez Simba !",
    enterValidEmail: "Entrez une adresse email valide",
    myOrders: "Mes commandes",
    noOrders: "Aucune commande pour l'instant",
    startShoppingDesc: "Commencez à acheter pour voir vos commandes ici.",
    browseProducts: "Parcourir les produits",
    pickupAt: "Retrait à",
    rateBranchHint: "Vous pourrez noter ce magasin une fois votre commande retirée.",
    dashTitle: "Tableau de bord magasin",
    dashAdmin: "Admin · tous les magasins",
    dashManager: "Vue gestionnaire",
    dashStaff: "Vue personnel",
    refresh: "Rafraîchir",
    ordersTab: "Commandes",
    inventoryTab: "Stock",
    bucketNew: "Nouvelles",
    bucketPreparing: "En préparation",
    bucketReady: "Prêtes",
    bucketDone: "Terminées",
    accept: "Accepter",
    startPreparing: "Commencer",
    markReady: "Marquer prête",
    markPickedUp: "Marquer retirée",
    flag: "Signaler",
    flagCustomer: "Signaler le client",
    assignToStaff: "Assigner au personnel...",
    showDetails: "Afficher les détails",
    hideDetails: "Masquer les détails",
    me: "Moi",
    noStaff: "Aucun personnel",
    items: "articles",
    item: "article",
    staffOnly: "Accès personnel uniquement",
    staffOnlyDesc: "Vous avez besoin de permissions personnel ou gestionnaire. Demandez à votre admin.",
    goHome: "Accueil",
    searchProductOrId: "Rechercher produit ou ID...",
    addProduct: "Ajouter un produit",
    addProductTitle: "Ajouter un produit à ce magasin",
    initialStock: "Stock initial",
    save: "Enregistrer",
    available: "Disponible",
    outOfStockLabel: "Rupture",
    remove: "Retirer",
    confirmRemove: "Retirer ce produit de l'inventaire du magasin ?",
    stockUpdated: "Stock mis à jour",
    productAdded: "Produit ajouté au magasin",
    productRemoved: "Produit retiré",
    noInventory: "Aucun produit dans ce magasin. Cliquez sur 'Ajouter un produit'.",
    adminTitle: "Attribution des rôles",
    adminDesc: "Promouvoir des utilisateurs comme gestionnaire ou personnel.",
    adminOnly: "Admin uniquement",
    adminOnlyDesc: "Vous n'avez pas accès à cette page.",
    user: "Utilisateur",
    role: "Rôle",
    branch: "Magasin",
    grantRole: "Attribuer le rôle",
    granting: "Attribution...",
    existingRoles: "Rôles existants",
    yourUserId: "Votre ID utilisateur :",
    branchStaff: "Personnel",
    branchManager: "Gestionnaire",
    admin: "Admin",
    customer: "Client",
    selectUser: "Sélectionner un utilisateur...",
    selectBranchPlaceholder: "Sélectionner un magasin",
    pretranslate: "Pré-traduire le catalogue",
    pretranslateDesc: "Une seule fois : traduit tous les noms en FR + RW pour basculement instantané.",
    translating: "Traduction...",
    translateAll: "Traduire tous les produits",
    translationDone: "Traductions sauvegardées. Changez de langue pour voir.",
    seedInventory: "Initialiser le stock",
    seedInventoryDesc: "Remplir chaque magasin avec un stock de départ (une seule fois).",
    seedNow: "Initialiser",
    seeded: "Magasins approvisionnés.",
    askSimba: "Demander à Simba AI",
    aiSubtitle: "Votre assistant shopping",
    aiGreeting: "Salut ! 👋 Je suis Simba — votre assistant IA. Demandez-moi tout : idées de repas, produits, prix !",
    aiPlaceholder: "Posez une question sur les produits...",
    tryAsking: "Essayez",
    thinking: "réflexion...",
    rateThisBranch: "Évaluer ce magasin",
    leaveComment: "Laisser un commentaire (facultatif)",
    submitReview: "Envoyer l'avis",
    reviewThanks: "Merci pour votre avis !",
    alreadyReviewed: "Vous avez déjà évalué cette commande.",
  },
  RW: {
    search: "Shaka ibicuruzwa, amazina...",
    cart: "Ikarita",
    signIn: "Injira",
    signUp: "Iyandikishe",
    signOut: "Sohoka",
    categories: "Ibyiciro",
    allProducts: "Ibicuruzwa byose",
    home: "Ahabanza",
    products: "Ibicuruzwa",
    orders: "Amateka yanjye",
    branchDashboard: "Ipaji y'ibyabaye",
    adminRoles: "Admin · Inshingano",
    account: "Konti",
    location: "Kigali, Rwanda",
    heroTitleA: "Ibiribwa mu",
    heroTitleB: "minota.",
    heroSubtitle: "Gura ibiribwa bishya by'u Rwanda wishyure na MoMo, ufate ku iduka rya Simba ryegereye.",
    startShopping: "Tangira kugura",
    fastDelivery: "Ifate ryihuse",
    fastDeliveryDesc: "Biteguye mu munota 60",
    securePayment: "Kwishyura kwizewe",
    securePaymentDesc: "MoMo na karita byemerwa",
    convenientPickup: "Amaduka 9",
    convenientPickupDesc: "Fata ahantu hose i Kigali",
    shopByCategory: "Gura ku byiciro",
    featuredProducts: "Ibyaranzwe",
    viewAll: "Reba byose",
    trustedBy: "Byizewe n'abakiriya 10,000+ i Kigali",
    ourBranches: "Amaduka yacu",
    addToCart: "Shyira mu ikarita",
    outOfStock: "Birashize",
    inStock: "Birahari",
    emptyCart: "Ikarita yawe ntakintu irimo",
    exploreProducts: "Reba ibicuruzwa",
    subtotal: "Igiteranyo",
    delivery: "Gutanga",
    free: "UBUSA",
    total: "Hose",
    proceedToPay: "Komeza kwishyura",
    loginToCheckout: "Injira kugira ngo urangize",
    checkout: "Ishura",
    sortBy: "Tondeka",
    popularity: "Ibikunzwe",
    lowToHigh: "Igiciro: Gito → Kinini",
    highToLow: "Igiciro: Kinini → Gito",
    noProducts: "Nta bicuruzwa bihuye n'ibyo ushaka.",
    productsFound: "ibicuruzwa",
    recommended: "Ibyatoranyijwe",
    pickupBranch: "Iduka ryo gufata",
    selectBranch: "Hitamo iduka",
    chooseBranch: "Hitamo iduka uzafataho ibyaguzwe",
    branchHint: "Tuzategura ibyaguzwe kugira ngo ubifatire hano.",
    pickupTime: "Igihe cyo gufata",
    pickupToday: "Uyu munsi",
    pickupTomorrow: "Ejo",
    chooseTime: "Hitamo igihe cyo gufata",
    yourDetails: "Amakuru yawe",
    fullName: "Amazina yose",
    phoneNumber: "Nimero ya telefoni",
    momoNumber: "Nimero ya MoMo",
    momoHint: "Ubutumwa bwo kwishyura buzoherezwa kuri iyi nimero.",
    notesOptional: "Inyandiko (si itegeko)",
    notesPlaceholder: "Amabwiriza yihariye...",
    deposit: "Avansi yo gufata",
    depositExplain: "Avansi nto irinda ko abakozi babika ibyaguzwe ku busa.",
    payDeposit: "Ishyura avansi",
    processing: "Bitunganywa...",
    momoPrompt: "MoMo yoherejwe",
    momoPromptDesc: "Emeza kuri telefoni yawe kugira ngo wuzuze avansi.",
    confirmPayment: "Emeza kwishyura",
    cancel: "Hagarika",
    orderPlaced: "Itegeko ryashyizweho!",
    orderPlacedDesc: "Iduka ryamenyeshejwe kandi ririmo gutegura ibyaguzwe.",
    continueShopping: "Komeza kugura",
    orderSummary: "Incamake y'itegeko",
    subtotalLabel: "Igiteranyo",
    payNow: "Ishyura",
    minOrder: "Ongeraho byibuze ikintu kimwe.",
    invalidMomo: "Andika nimero ya MoMo nziza yo mu Rwanda (urugero 07XXXXXXXX)",
    welcomeBack: "Murakaza neza",
    createAccount: "Fungura konti yawe",
    signInDesc: "Injira ukomeze kugura",
    signUpDesc: "Iyandikishe kuri Simba mu masegonda macye",
    email: "Imeyili",
    password: "Ijambobanga",
    confirmPassword: "Subiramo ijambobanga",
    forgotPassword: "Wibagiwe ijambobanga?",
    continueWithGoogle: "Komeza na Google",
    orContinueWith: "cyangwa koresha imeyili",
    noAccount: "Nta konti ufite?",
    haveAccount: "Usanzwe ufite konti?",
    register: "Iyandikishe",
    login: "Injira",
    backToShop: "Subira mu iduka",
    resetPassword: "Hindura ijambobanga",
    resetPasswordDesc: "Andika imeyili yawe wakire link.",
    sendResetLink: "Ohereza link",
    resetLinkSent: "Reba imeyili yawe.",
    setNewPassword: "Shyiraho ijambobanga rishya",
    newPassword: "Ijambobanga rishya",
    updatePassword: "Hindura",
    passwordUpdated: "Ijambobanga ryahindutse. Winjiye.",
    invalidCredentials: "Imeyili cyangwa ijambobanga sibyo",
    passwordTooShort: "Ijambobanga rigomba kuba rifite byibuze inyuguti 6",
    passwordsMismatch: "Amabanga ntahuye",
    accountCreated: "Konti yashyizweho. Murakaza neza kuri Simba!",
    enterValidEmail: "Andika imeyili nziza",
    myOrders: "Amateka yanjye",
    noOrders: "Nta bicuruzwa byaguzwe",
    startShoppingDesc: "Tangira kugura ngo ubirebe hano.",
    browseProducts: "Reba ibicuruzwa",
    pickupAt: "Bizafatirwa",
    rateBranchHint: "Uzashobora gutanga amanota nyuma yo gufata ibyaguzwe.",
    dashTitle: "Ipaji y'iduka",
    dashAdmin: "Admin · amaduka yose",
    dashManager: "Reba nk'umuyobozi",
    dashStaff: "Reba nk'umukozi",
    refresh: "Vugurura",
    ordersTab: "Ibyategetswe",
    inventoryTab: "Ububiko",
    bucketNew: "Bishya",
    bucketPreparing: "Biratunganywa",
    bucketReady: "Biteguye",
    bucketDone: "Byarangiye",
    accept: "Emeza",
    startPreparing: "Tangira gutegura",
    markReady: "Byiteguye",
    markPickedUp: "Byafashwe",
    flag: "Tanga ikimenyetso",
    flagCustomer: "Shyira ikimenyetso ku mukiriya",
    assignToStaff: "Tanga umukozi...",
    showDetails: "Erekana ibisobanuro",
    hideDetails: "Hisha ibisobanuro",
    me: "Njye",
    noStaff: "Nta bakozi",
    items: "ibintu",
    item: "ikintu",
    staffOnly: "Ku bakozi gusa",
    staffOnlyDesc: "Ukeneye uburenganzira bw'umukozi cyangwa umuyobozi. Saba admin yawe.",
    goHome: "Subira ahabanza",
    searchProductOrId: "Shaka izina cyangwa ID...",
    addProduct: "Ongeraho igicuruzwa",
    addProductTitle: "Ongeraho igicuruzwa kuri iri duka",
    initialStock: "Umubare wa mbere",
    save: "Bika",
    available: "Birahari",
    outOfStockLabel: "Birashize",
    remove: "Kuraho",
    confirmRemove: "Ukuraho iki gicuruzwa mu ububiko bw'iduka?",
    stockUpdated: "Ububiko bwahinduwe",
    productAdded: "Igicuruzwa cyongeweho",
    productRemoved: "Igicuruzwa cyakuweho",
    noInventory: "Iri duka nta gicuruzwa rifite. Kanda 'Ongeraho igicuruzwa'.",
    adminTitle: "Gutanga inshingano",
    adminDesc: "Tanga umuyobozi cyangwa umukozi.",
    adminOnly: "Ku admin gusa",
    adminOnlyDesc: "Nta burenganzira ufite kuri iyi paji.",
    user: "Umukoresha",
    role: "Inshingano",
    branch: "Iduka",
    grantRole: "Tanga inshingano",
    granting: "Bitangwa...",
    existingRoles: "Inshingano zihari",
    yourUserId: "ID yawe:",
    branchStaff: "Umukozi w'iduka",
    branchManager: "Umuyobozi w'iduka",
    admin: "Admin",
    customer: "Umukiriya",
    selectUser: "Hitamo umukoresha...",
    selectBranchPlaceholder: "Hitamo iduka",
    pretranslate: "Hindura ibicuruzwa byose",
    pretranslateDesc: "Inshuro imwe: hindura amazina yose mu FR + RW kugirango bihinduke vuba.",
    translating: "Birahindurwa...",
    translateAll: "Hindura ibicuruzwa byose",
    translationDone: "Bibitswe. Hindura ururimi urebe.",
    seedInventory: "Shyira ububiko bw'intangiriro",
    seedInventoryDesc: "Uzuza buri duka n'ibicuruzwa by'intangiriro (inshuro imwe).",
    seedNow: "Shyiraho",
    seeded: "Amaduka yuzuyemo.",
    askSimba: "Baza Simba AI",
    aiSubtitle: "Umufasha wawe",
    aiGreeting: "Muraho! 👋 Ndi Simba — umufasha wawe wa AI. Mbaza kuri ibyo ushaka kurya, ibiciro, n'ibindi!",
    aiPlaceholder: "Baza ku bicuruzwa...",
    tryAsking: "Gerageza ubaze",
    thinking: "ndabitekereza...",
    rateThisBranch: "Tanga amanota kuri iri duka",
    leaveComment: "Andika igitekerezo (si itegeko)",
    submitReview: "Ohereza",
    reviewThanks: "Murakoze ku gitekerezo!",
    alreadyReviewed: "Wamaze gutanga amanota.",
  },
} as const;

// ===== Product translation cache =====
type ProductTr = { name: string; category: string };
const trCache: Record<Language, Map<number, ProductTr>> = {
  EN: new Map(),
  FR: new Map(),
  RW: new Map(),
};
const categoryCache: Record<Language, Map<string, string>> = {
  EN: new Map(),
  FR: new Map(),
  RW: new Map(),
};

interface LanguageContextType {
  lang: Language;
  t: (typeof translations)["EN"];
  changeLanguage: (l: Language) => void;
  trProductName: (id: number, fallback: string) => string;
  trCategory: (cat: string) => string;
  refreshProductTranslations: () => Promise<void>;
}

const LanguageContext = React.createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = React.useState<Language>("EN");
  const [, setTick] = React.useState(0);
  const forceRender = React.useCallback(() => setTick((x) => x + 1), []);

  React.useEffect(() => {
    const saved = localStorage.getItem("simba_lang") as Language | null;
    if (saved && translations[saved]) setLang(saved);
  }, []);

  const loadTranslations = React.useCallback(async () => {
    const { data } = await supabase
      .from("products_i18n")
      .select("product_id, lang, name, category");
    if (!data) return;
    (["EN", "FR", "RW"] as Language[]).forEach((l) => {
      trCache[l].clear();
      categoryCache[l].clear();
    });
    data.forEach((row) => {
      const l = (row.lang as Language) ?? "EN";
      if (!translations[l]) return;
      trCache[l].set(row.product_id, {
        name: row.name ?? "",
        category: row.category ?? "",
      });
      if (row.category) {
        // map source category (English) to translated; we store EN->translated by using EN row as source
      }
    });
    // Build category map: for each EN product row, take its category as source key,
    // and for each language find category text from the row of same product_id.
    const enRows = data.filter((r) => r.lang === "EN");
    enRows.forEach((en) => {
      if (!en.category) return;
      (["EN", "FR", "RW"] as Language[]).forEach((l) => {
        const tr = trCache[l].get(en.product_id);
        if (tr?.category && !categoryCache[l].has(en.category!)) {
          categoryCache[l].set(en.category!, tr.category);
        }
      });
    });
    forceRender();
  }, [forceRender]);

  React.useEffect(() => {
    loadTranslations();
  }, [loadTranslations]);

  const changeLanguage = React.useCallback((l: Language) => {
    setLang(l);
    localStorage.setItem("simba_lang", l);
  }, []);

  const trProductName = React.useCallback(
    (id: number, fallback: string) => {
      const v = trCache[lang].get(id);
      return v?.name || fallback;
    },
    [lang],
  );

  const trCategory = React.useCallback(
    (cat: string) => {
      if (lang === "EN") return cat;
      return categoryCache[lang].get(cat) || cat;
    },
    [lang],
  );

  return (
    <LanguageContext.Provider
      value={{
        lang,
        t: translations[lang],
        changeLanguage,
        trProductName,
        trCategory,
        refreshProductTranslations: loadTranslations,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = React.useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
